
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
data:
  init.js: |
    db = db.getSiblingDB('logistics-tracker');
    db.createCollection('test');

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2   # ✅ AWS EBS default storage class
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: MONGO_INITDB_DATABASE
              value: logistics-tracker
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-storage
            - mountPath: /docker-entrypoint-initdb.d
              name: mongo-init
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
        - name: mongo-init
          configMap:
            name: mongo-init-script

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
